### ISSUE TITLE
I have a small question in self-driving-ai，I hope to answer it, thank you

### ISSUE THREAD

**Issue by nfhe** [m-ulmestrand/self-driving-ai#6]
I am also learning AI recently, but I am a novice. Hope to give a tutorial on how to run the program, and program display have not racetrack12.npy!thank you.

**Comment by m-ulmestrand** [comment]
Hey,

Nice to see that you're interested! racetrack12.npy is added by now. I've been doing this project mostly for myself, so the code is not as well-commented or structured as it should be. I can definitely improve on some things and add a walkthrough of how to run the main script, training etc. I'll keep you updated with changes.

Thanks!

**Comment by nfhe** [comment]
> Hey,
> 
> Nice to see that you're interested! racetrack12.npy is added by now. I've been doing this project mostly for myself, so the code is not as well-commented or structured as it should be. I can definitely improve on some things and add a walkthrough of how to run the main script, training etc. I'll keep you updated with changes.
> 
> Thanks!

Hi,teather.

Thank you for your reply. I am very interested in DRL control. I hope the teacher can update it as soon as possible so that I can learn more knowledge.

thank

**Comment by m-ulmestrand** [comment]
I've added a small tutorial to the README.md file. There's also many more comments in the code, so you can also take a look there and find some details.

Cheers

**Comment by nfhe** [comment]
Hi,man
Thank you for yours code and tutorial.I believe you can learn more about self-driving-ai.
